name: 'Get an app token in an Actions workflow.'
description: Useful for remedying the problem of restricted access tokens, especially on PRs from forks.
author: Jacob Morgan
inputs:
  app_id:
    description: ID of the GitHub App.
    required: true
  app_private_key:
    description: Private key of the GitHub App Base64 encoded. (You can apply this encoding in the terminal `cat key.pem | base64`)
    required: true
  repository:
    description: The full name of the repository for which the token will be requested (defaults to the current repository).
    required: false
  github_api_url:
    description: The GitHub API URL (defaults to $GITHUB_API_URL 'https://api.github.com')
    required: false
outputs:
  token:
    description: An installation token for the GitHub App on the requested repository.
branding:
  color: 'white'
  icon: 'unlock'
runs:
  using: 'docker'
  image: 'Dockerfile'
